/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaFormulario;

import Controlador.Controlador;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

/**
 *
 * @author Ramon Valencia
 */
public class formulario extends javax.swing.JFrame {

    public Dimension tamañoFrame = new Dimension(1200, 800);
    public Controlador controlador;
    /**
     * Creates new form formulario
     */
    public formulario() {
        controlador = new Controlador();
        setSize(tamañoFrame);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        generarPanelCentral();
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }
    
    public void generarPanelCentral() {
        JPanel panelCentral = new JPanel(new BorderLayout());
        generarPanelIzquierdo(panelCentral);
        add(panelCentral);
    }
    
    public void generarPanelIzquierdo(JPanel panelCentral) {
        JPanel panelIzquierdo = new JPanel(new GridLayout(0, 2));
        JLabel labelNombre = new JLabel("Nombre: ");
        JTextField campoNombre = new JTextField(20);
        JLabel labelApellido = new JLabel("Apellido: ");
        JTextField campoApellido = new JTextField(20);
        JLabel labelCorreo = new JLabel("Correo: ");
        JTextField campoCorreo = new JTextField(20);
        panelIzquierdo.add(labelNombre);
        panelIzquierdo.add(campoNombre);
        panelIzquierdo.add(labelApellido);
        panelIzquierdo.add(campoApellido);
        panelIzquierdo.add(labelCorreo);
        panelIzquierdo.add(campoCorreo);
        
        panelCentral.add(panelIzquierdo, BorderLayout.WEST);
        JButton botonAgregar = new JButton("Agregar Usuario");
        botonAgregar.addActionListener((ActionEvent e) -> {
            controlador.registrarUsuario(campoNombre.getText(), campoApellido.getText(), campoCorreo.getText());
        });
        panelCentral.add(botonAgregar);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
